apiVersion: v1
kind: Service
metadata:
    name: houssemdellaiproductsstoreonkubernetes
spec:
    type: LoadBalancer
    ports:
    - port: 3317 
    selector:
        app: houssemdellaiproductsstoreonkubernetes