apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 1
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image:  houssemdocker/webapp:1.0 # acrforaks2020.azurecr.io/webapp:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
          - name: ConnectionStrings__ProductsContext
            valueFrom:
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #ClusterIP #NodePort
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: webapp-ingress
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /api/hello-world
#         backend:
#           serviceName: mvc-service
#           servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: mvc
data:
  # db-connection-string: Server=tcp:mssql-paas.database.windows.net,1433;Initial Catalog=ProductsDB;Persist Security Info=False;User ID=houssem;Password=@Aa123456;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
  db-connection-string: Server=mssql-service;Database=ProdcutsDB;User ID=SA;Password=@Aa123456;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
      # image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
      # image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
      # image: microsoft/mssql-server-linux
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "@Aa123456"
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30200
  type: NodePort
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi