apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: houssemdocker/webapp:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
          - name: ConnectionStrings__ProductsContext
            valueFrom:
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: webapp-ingress
#   namespace: default
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /api/hello-world
#         backend:
#           serviceName: mvc-service
#           servicePort: 80