apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 3
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: acrinseec.azurecr.io/inseecapp:1.0
        # image: houssemdocker/mvc-app:1.0 
        # image: __ACR_NAME__.azurecr.io/webapp:1.__Build.BuildId__
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        env:
          - name: ConnectionStrings__ProductsContext
            valueFrom:
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
        #     secretKeyRef:
        #       name: mssql-secret
        #       key: db-connection-string-secret
---
kind: Service
apiVersion: v1
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer #NodePort
